# Site settings
title: iAzrael的私家书架
email: atlas@imatlas.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://imatlas.com" # the base hostname & protocol for your site
twitter_username: imazrael
github_username:  iazrael

# Build settings
markdown: kramdown
