# Site settings
title: iAzrael的私家书架
email: atlas@imatlas.com
description: > # this means to ignore newlines until "baseurl:"
  所有用Markdown写的文字都会存在这里
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://imatlas.com" # the base hostname & protocol for your site
twitter_username: imazrael
github_username:  iazrael

# Build settings
markdown: kramdown
